export const medecins = [
  {
    id: 1,
    nom: "Dr. Ngassa Pierre",
    specialite: "Dentiste",
    specialiteEn: "Dentist",
    ville: "Douala",
    note: 4.9,
    avis: 270,
    experience: "15 ans",
    clinique: "Clinique du Wouri",
    description: "Spécialiste en soins dentaires préventifs et esthétiques.",
    descriptionEn: "Specialist in preventive and aesthetic dental care.",
    prochainRdv: "Aujourd'hui, 14:00",
    prochainRdvEn: "Today, 2:00 PM",
    disponible: true,
    favoris: false,
    modes: ["Video", "Présentiel"],
  },
  {
    id: 2,
    nom: "Dr. Kamdem Marie",
    specialite: "Cardiologue",
    specialiteEn: "Cardiologist",
    ville: "Yaoundé",
    note: 4.8,
    avis: 150,
    experience: "20 ans",
    clinique: "Hôpital Central",
    description: "Experte en santé cardiaque et maladies cardiovasculaires.",
    descriptionEn: "Expert in cardiac health and cardiovascular diseases.",
    prochainRdv: "Demain, 10:00",
    prochainRdvEn: "Tomorrow, 10:00 AM",
    disponible: true,
    favoris: true,
    modes: ["Video", "Présentiel"],
  },
  {
    id: 3,
    nom: "Dr. Bello Ahmed",
    specialite: "Généraliste",
    specialiteEn: "General Practitioner",
    ville: "Douala",
    note: 4.7,
    avis: 130,
    experience: "12 ans",
    clinique: "Clinique La Grâce",
    description: "Médecin généraliste spécialisé en médecine préventive.",
    descriptionEn: "General practitioner specialized in preventive medicine.",
    prochainRdv: "Demain, 13:30",
    prochainRdvEn: "Tomorrow, 1:30 PM",
    disponible: false,
    favoris: false,
    modes: ["Présentiel"],
  },
  {
    id: 4,
    nom: "Dr. Ngo Sophie",
    specialite: "Pédiatre",
    specialiteEn: "Pediatrician",
    ville: "Yaoundé",
    note: 4.9,
    avis: 200,
    experience: "18 ans",
    clinique: "Clinique Bastos",
    description: "Spécialiste de la santé des enfants et adolescents.",
    descriptionEn: "Specialist in children and adolescent health.",
    prochainRdv: "Aujourd'hui, 16:00",
    prochainRdvEn: "Today, 4:00 PM",
    disponible: true,
    favoris: false,
    modes: ["Video", "Présentiel"],
  },
  {
    id: 5,
    nom: "Dr. Essomba Paul",
    specialite: "Dermatologue",
    specialiteEn: "Dermatologist",
    ville: "Douala",
    note: 4.6,
    avis: 95,
    experience: "10 ans",
    clinique: "Clinique du Wouri",
    description: "Expert en maladies de la peau et soins cosmétiques.",
    descriptionEn: "Expert in skin diseases and cosmetic care.",
    prochainRdv: "Demain, 11:00",
    prochainRdvEn: "Tomorrow, 11:00 AM",
    disponible: true,
    favoris: false,
    modes: ["Présentiel"],
  },
  {
    id: 6,
    nom: "Dr. Foka Jean",
    specialite: "Neurologue",
    specialiteEn: "Neurologist",
    ville: "Yaoundé",
    note: 4.8,
    avis: 110,
    experience: "16 ans",
    clinique: "Hôpital Général",
    description: "Spécialiste du cerveau et du système nerveux.",
    descriptionEn: "Specialist in brain and nervous system conditions.",
    prochainRdv: "Demain, 9:00",
    prochainRdvEn: "Tomorrow, 9:00 AM",
    disponible: true,
    favoris: true,
    modes: ["Video", "Présentiel"],
  },
  {
    id: 7,
    nom: "Dr. Mbarga Claire",
    specialite: "Ophtalmologue",
    specialiteEn: "Ophthalmologist",
    ville: "Douala",
    note: 4.7,
    avis: 88,
    experience: "14 ans",
    clinique: "Clinique Monkam",
    description: "Spécialiste de la santé oculaire et des troubles visuels.",
    descriptionEn: "Specialist in eye health and visual disorders.",
    prochainRdv: "Aujourd'hui, 17:30",
    prochainRdvEn: "Today, 5:30 PM",
    disponible: true,
    favoris: false,
    modes: ["Présentiel"],
  },
  {
    id: 8,
    nom: "Dr. Tagne Marc",
    specialite: "Orthopédiste",
    specialiteEn: "Orthopedist",
    ville: "Yaoundé",
    note: 4.5,
    avis: 75,
    experience: "8 ans",
    clinique: "Hôpital Jamot",
    description: "Expert en troubles musculo-squelettiques et rééducation.",
    descriptionEn: "Expert in musculoskeletal disorders and rehabilitation.",
    prochainRdv: "Demain, 15:00",
    prochainRdvEn: "Tomorrow, 3:00 PM",
    disponible: false,
    favoris: false,
    modes: ["Présentiel"],
  },
];

export const specialites = [
  { label: "Toutes", labelEn: "All Specialties" },
  { label: "Généraliste", labelEn: "General Medicine" },
  { label: "Cardiologue", labelEn: "Cardiology" },
  { label: "Dermatologue", labelEn: "Dermatology" },
  { label: "Orthopédiste", labelEn: "Orthopedics" },
  { label: "Dentiste", labelEn: "Dentistry" },
  { label: "Pédiatre", labelEn: "Pediatrics" },
  { label: "Neurologue", labelEn: "Neurology" },
  { label: "Ophtalmologue", labelEn: "Ophthalmology" },
];