"""
Script de seed : 200 médicaments couramment utilisés au Cameroun.

Usage :
    python seed_medicaments.py

Insère les médicaments dans la table 'medicaments' via une connexion directe à PostgreSQL.
Nécessite la variable DATABASE_URL dans .env ou un fichier .env à la racine du backend.
"""

import os
import sys

from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://nere_user:nere_pass@localhost:5432/nere_health")

MEDICAMENTS = [
    # ── ANTIPALUDÉENS ──
    ("Nivaquine", "Chloroquine", "100 mg", "Comprimé", "Antipaludéen"),
    ("Nivaquine", "Chloroquine", "200 mg", "Comprimé", "Antipaludéen"),
    ("Nivaquine S", "Chloroquine + Sulfadoxine-Pyriméthamine", "200/25 mg", "Comprimé", "Antipaludéen"),
    ("Coartem", "Arteméther-Luméfantrine", "20/120 mg", "Comprimé", "Antipaludéen"),
    ("Coartem", "Arteméther-Luméfantrine", "80/480 mg", "Comprimé", "Antipaludéen"),
    ("Paludéx", "Dihydroartémisinine-Pipéraquine", "40/320 mg", "Comprimé", "Antipaludéen"),
    ("Malarex", "Amodiaquine", "153 mg", "Comprimé", "Antipaludéen"),
    ("Malarex", "Amodiaquine", "50 mg", "Comprimé enfant", "Antipaludéen"),
    ("Fansidar", "Sulfadoxine-Pyriméthamine", "500/25 mg", "Comprimé", "Antipaludéen"),
    ("Néoxyvarine", "Proguanil-Atovaquone", "250/100 mg", "Comprimé", "Antipaludéen"),
    ("Riamet", "Arteméther-Luméfantrine", "20/120 mg", "Comprimé", "Antipaludéen"),
    ("Artesunate", "Artesunate", "100 mg", "Comprimé", "Antipaludéen"),
    ("Artesunate", "Artesunate", "60 mg", "Injectable", "Antipaludéen"),
    ("Chloroquine phosphate", "Chloroquine", "250 mg", "Comprimé", "Antipaludéen"),
    ("Quinine", "Sulfate de quinine", "300 mg", "Comprimé", "Antipaludéen"),
    ("Quinine", "Sulfate de quinine", "600 mg", "Injectable", "Antipaludéen"),
    ("Malarone", "Atovaquone-Proguanil", "250/100 mg", "Comprimé", "Antipaludéen"),
    ("Lariam", "Méfloquine", "250 mg", "Comprimé", "Antipaludéen"),
    ("Plaquenil", "Hydroxychloroquine", "200 mg", "Comprimé", "Antipaludéen"),

    # ── ANTIBIOTIQUES ──
    ("Amoxicilline", "Amoxicilline", "500 mg", "Gélule", "Antibiotique"),
    ("Amoxicilline", "Amoxicilline", "1 g", "Comprimé", "Antibiotique"),
    ("Amoxicilline", "Amoxicilline", "250 mg/5 ml", "Sirop", "Antibiotique"),
    ("Amoxicilline", "Amoxicilline", "125 mg/5 ml", "Sirop", "Antibiotique"),
    ("Augmentin", "Amoxicilline-Acide clavulanique", "1 g/125 mg", "Comprimé", "Antibiotique"),
    ("Augmentin", "Amoxicilline-Acide clavulanique", "625 mg", "Comprimé", "Antibiotique"),
    ("Augmentin", "Amoxicilline-Acide clavulanique", "457 mg/5 ml", "Sirop", "Antibiotique"),
    ("Augmentin", "Amoxicilline-Acide clavulanique", "228 mg/5 ml", "Sirop", "Antibiotique"),
    ("Ciprofloxacine", "Ciprofloxacine", "500 mg", "Comprimé", "Antibiotique"),
    ("Ciprofloxacine", "Ciprofloxacine", "200 mg/100 ml", "Solution injectable", "Antibiotique"),
    ("Ciproxine", "Ciprofloxacine", "500 mg", "Comprimé pelliculé", "Antibiotique"),
    ("Ciproxine", "Ciprofloxacine", "250 mg", "Comprimé pelliculé", "Antibiotique"),
    ("Doxycycline", "Doxycycline", "100 mg", "Gélule", "Antibiotique"),
    ("Doxycycline", "Doxycycline", "50 mg", "Gélule", "Antibiotique"),
    ("Érythromycine", "Érythromycine", "500 mg", "Comprimé", "Antibiotique"),
    ("Érythromycine", "Érythromycine", "200 mg/5 ml", "Sirop", "Antibiotique"),
    ("Métrodinazole", "Métrodinazole", "250 mg", "Comprimé", "Antibiotique"),
    ("Métrodinazole", "Métrodinazole", "500 mg", "Comprimé", "Antibiotique"),
    ("Métrodinazole", "Métrodinazole", "500 mg/100 ml", "Solution injectable", "Antibiotique"),
    ("Flagyl", "Métrodinazole", "500 mg", "Comprimé", "Antibiotique"),
    ("Ofloxacine", "Ofloxacine", "200 mg", "Comprimé", "Antibiotique"),
    ("Ofloxacine", "Ofloxacine", "400 mg", "Comprimé", "Antibiotique"),
    ("Norfloxine", "Norfloxacine", "400 mg", "Comprimé", "Antibiotique"),
    ("Zinnat", "Céfuroxime", "500 mg", "Comprimé pelliculé", "Antibiotique"),
    ("Zinnat", "Céfuroxime", "125 mg/5 ml", "Sirop", "Antibiotique"),
    ("Zinnat", "Céfuroxime", "250 mg", "Comprimé pelliculé", "Antibiotique"),
    ("Kéflex", "Céfaléxine", "500 mg", "Gélule", "Antibiotique"),
    ("Kéflex", "Céfaléxine", "250 mg/5 ml", "Sirop", "Antibiotique"),
    ("Céftriaxone", "Céftriaxone", "1 g", "Injectable", "Antibiotique"),
    ("Céftriaxone", "Céftriaxone", "500 mg", "Injectable", "Antibiotique"),
    ("Gentamicine", "Gentamicine", "80 mg/2 ml", "Solution injectable", "Antibiotique"),
    ("Gentamicine", "Gentamicine", "0,3%", "Collyre", "Antibiotique"),
    ("Tienam", "Imipénème-Cilastatine", "500 mg", "Injectable", "Antibiotique"),
    ("Kanamycine", "Kanamycine", "500 mg", "Injectable", "Antibiotique"),
    ("Azithromycine", "Azithromycine", "500 mg", "Comprimé", "Antibiotique"),
    ("Azithromycine", "Azithromycine", "200 mg/5 ml", "Sirop", "Antibiotique"),
    ("Azithromycine", "Azithromycine", "250 mg", "Comprimé", "Antibiotique"),
    ("Clindamycine", "Clindamycine", "300 mg", "Gélule", "Antibiotique"),
    ("Clindamycine", "Clindamycine", "150 mg/5 ml", "Sirop", "Antibiotique"),
    ("Metronidazole benzoate", "Métrodinazole", "200 mg/5 ml", "Suspension buvable", "Antibiotique"),
    ("Sulfaméthoxazole-Triméthoprime", "Sulfaméthoxazole-Triméthoprime", "400/80 mg", "Comprimé", "Antibiotique"),
    ("Bactrim", "Sulfaméthoxazole-Triméthoprime", "400/80 mg", "Comprimé", "Antibiotique"),
    ("Bactrim", "Sulfaméthoxazole-Triméthoprime", "200/40 mg/5 ml", "Sirop", "Antibiotique"),

    # ── ANTIDIABÉTIQUES ──
    ("Glucophage", "Metformine", "850 mg", "Comprimé", "Antidiabétique oral"),
    ("Glucophage", "Metformine", "500 mg", "Comprimé", "Antidiabétique oral"),
    ("Glucophage", "Metformine", "1 g", "Comprimé", "Antidiabétique oral"),
    ("Metformine Mylan", "Metformine", "1000 mg", "Comprimé pelliculé", "Antidiabétique oral"),
    ("Metformine EG", "Metformine", "850 mg", "Comprimé pelliculé", "Antidiabétique oral"),
    ("Diamicron", "Gliclazide", "30 mg", "Comprimé à libération modifiée", "Antidiabétique oral"),
    ("Diamicron", "Gliclazide", "80 mg", "Comprimé sécable", "Antidiabétique oral"),
    ("Gliclazide Mylan", "Gliclazide", "80 mg", "Comprimé", "Antidiabétique oral"),
    ("Amaryl", "Glimépiride", "1 mg", "Comprimé", "Antidiabétique oral"),
    ("Amaryl", "Glimépiride", "2 mg", "Comprimé", "Antidiabétique oral"),
    ("Amaryl", "Glimépiride", "3 mg", "Comprimé", "Antidiabétique oral"),
    ("Januvia", "Sitagliptine", "100 mg", "Comprimé pelliculé", "Antidiabétique oral"),
    ("Jardiance", "Empagliflozine", "10 mg", "Comprimé pelliculé", "Antidiabétique oral"),
    ("Jardiance", "Empagliflozine", "25 mg", "Comprimé pelliculé", "Antidiabétique oral"),
    ("Insuline Actrapid", "Insuline humaine", "100 UI/ml", "Solution injectable", "Insuline"),
    ("Insuline Lantus", "Insuline glargine", "100 UI/ml", "Solution injectable", "Insuline"),
    ("Insuline Humalog", "Insuline lispro", "100 UI/ml", "Solution injectable", "Insuline"),
    ("Mixtard", "Insuline humaine", "100 UI/ml", "Solution injectable", "Insuline"),
    ("Novorapid", "Insuline aspart", "100 UI/ml", "Solution injectable", "Insuline"),
    ("Levemir", "Insuline détémir", "100 UI/ml", "Solution injectable", "Insuline"),

    # ── ANTIHYPERTENSEURS ──
    ("Amlo", "Amlodipine", "5 mg", "Comprimé", "Antihypertenseur"),
    ("Amlo", "Amlodipine", "10 mg", "Comprimé", "Antihypertenseur"),
    ("Norvasc", "Amlodipine", "5 mg", "Comprimé", "Antihypertenseur"),
    ("Norvasc", "Amlodipine", "10 mg", "Comprimé", "Antihypertenseur"),
    ("Enalapril", "Enalapril", "10 mg", "Comprimé", "IEC"),
    ("Enalapril", "Enalapril", "20 mg", "Comprimé", "IEC"),
    ("Renitec", "Enalapril", "20 mg", "Comprimé", "IEC"),
    ("Lisinopril", "Lisinopril", "10 mg", "Comprimé", "IEC"),
    ("Lisinopril", "Lisinopril", "20 mg", "Comprimé", "IEC"),
    ("Cozaar", "Losartan", "50 mg", "Comprimé", "ARA II"),
    ("Cozaar", "Losartan", "100 mg", "Comprimé", "ARA II"),
    ("Losartan Mylan", "Losartan", "50 mg", "Comprimé", "ARA II"),
    ("Atenol", "Aténolol", "50 mg", "Comprimé", "Bêta-bloquant"),
    ("Atenol", "Aténolol", "100 mg", "Comprimé", "Bêta-bloquant"),
    ("Aténolol EG", "Aténolol", "50 mg", "Comprimé", "Bêta-bloquant"),
    ("Propranolol", "Propranolol", "40 mg", "Comprimé", "Bêta-bloquant"),
    ("Propranolol", "Propranolol", "80 mg", "Comprimé", "Bêta-bloquant"),
    ("Candesartan", "Candesartan", "8 mg", "Comprimé", "ARA II"),
    ("Candesartan", "Candesartan", "16 mg", "Comprimé", "ARA II"),
    ("Ramipril", "Ramipril", "5 mg", "Comprimé", "IEC"),
    ("Ramipril", "Ramipril", "10 mg", "Comprimé", "IEC"),
    ("Adalat", "Nifédipine", "20 mg", "Gélule", "Inhibiteur calcique"),
    ("Adalat", "Nifédipine", "30 mg", "Comprimé", "Inhibiteur calcique"),
    ("Hydrochlorothiazide", "Hydrochlorothiazide", "25 mg", "Comprimé", "Diurétique"),
    ("Hydrochlorothiazide", "Hydrochlorothiazide", "50 mg", "Comprimé", "Diurétique"),
    ("Furosémide", "Furosémide", "40 mg", "Comprimé", "Diurétique"),
    ("Furosémide", "Furosémide", "20 mg/2 ml", "Solution injectable", "Diurétique"),
    ("Lasilix", "Furosémide", "40 mg", "Comprimé", "Diurétique"),
    ("Spironolactone", "Spironolactone", "25 mg", "Comprimé", "Diurétique épargneur de potassium"),
    ("Spironolactone", "Spironolactone", "50 mg", "Comprimé", "Diurétique épargneur de potassium"),

    # ── ANTALGIQUES / DOULEUR ──
    ("Doliprane", "Paracétamol", "500 mg", "Comprimé", "Antalgique"),
    ("Doliprane", "Paracétamol", "1 g", "Comprimé", "Antalgique"),
    ("Doliprane", "Paracétamol", "2,4%", "Sirop", "Antalgique"),
    ("Doliprane", "Paracétamol", "100 mg", "Suppositoire", "Antalgique"),
    ("Efferalgan", "Paracétamol", "500 mg", "Comprimé effervescent", "Antalgique"),
    ("Efferalgan", "Paracétamol", "1 g", "Comprimé effervescent", "Antalgique"),
    ("Paracétamol Mylan", "Paracétamol", "500 mg", "Gélule", "Antalgique"),
    ("Ibuprofène", "Ibuprofène", "200 mg", "Comprimé", "AINS"),
    ("Ibuprofène", "Ibuprofène", "400 mg", "Comprimé", "AINS"),
    ("Ibuprofène", "Ibuprofène", "600 mg", "Comprimé pelliculé", "AINS"),
    ("Advil", "Ibuprofène", "200 mg", "Gélule", "AINS"),
    ("Advil", "Ibuprofène", "400 mg", "Comprimé", "AINS"),
    ("Nurofen", "Ibuprofène", "200 mg", "Comprimé pelliculé", "AINS"),
    ("Nurofen", "Ibuprofène", "400 mg", "Comprimé pelliculé", "AINS"),
    ("Aspégic", "Acide acétylsalicylique", "100 mg", "Comprimé pelliculé", "AINS"),
    ("Aspégic", "Acide acétylsalicylique", "500 mg", "Poudre", "AINS"),
    ("Kardégic", "Acide acétylsalicylique", "75 mg", "Comprimé gastro-résistant", "AINS"),
    ("Voltarène", "Diclofénac", "50 mg", "Comprimé pelliculé", "AINS"),
    ("Voltarène", "Diclofénac", "75 mg/3 ml", "Solution injectable", "AINS"),
    ("Voltarène", "Diclofénac", "1%", "Gel", "AINS"),
    ("Tramadol", "Tramadol", "50 mg", "Gélule", "Opioïde faible"),
    ("Tramadol", "Tramadol", "100 mg", "Gélule", "Opioïde faible"),
    ("Tramal", "Tramadol", "50 mg", "Gouttes", "Opioïde faible"),
    ("Tramal", "Tramadol", "100 mg/2 ml", "Solution injectable", "Opioïde faible"),
    ("Néoproxène", "Néoproxène", "250 mg", "Comprimé pelliculé", "AINS"),
    ("Néoproxène", "Néoproxène", "500 mg", "Comprimé pelliculé", "AINS"),
    ("Kétorolac", "Kétorolac", "10 mg", "Comprimé", "AINS"),
    ("Kétorolac", "Kétorolac", "30 mg/ml", "Solution injectable", "AINS"),
    ("Piroxicam", "Piroxicam", "20 mg", "Comprimé", "AINS"),
    ("Piroxicam", "Piroxicam", "0,5%", "Gel", "AINS"),

    # ── ANTI-ASTHMATIQUES / RESPIRATOIRES ──
    ("Ventoline", "Salbutamol", "100 µg/dose", "Aérosol dosé", "Bronchodilatateur"),
    ("Ventoline", "Salbutamol", "4 mg", "Comprimé", "Bronchodilatateur"),
    ("Ventoline", "Salbutamol", "2 mg/5 ml", "Sirop", "Bronchodilatateur"),
    ("Salbutamol Arrow", "Salbutamol", "100 µg/dose", "Aérosol dosé", "Bronchodilatateur"),
    ("Pulmicort", "Budesonide", "200 µg/dose", "Aérosol dosé", "Corticoïde inhalé"),
    ("Pulmicort", "Budesonide", "400 µg/dose", "Aérosol dosé", "Corticoïde inhalé"),
    ("Pulmicort Turbuhaler", "Budesonide", "100 µg/dose", "Poudre inhalée", "Corticoïde inhalé"),
    ("Pulmicort Turbuhaler", "Budesonide", "200 µg/dose", "Poudre inhalée", "Corticoïde inhalé"),
    ("Sérétide", "Salmétérol-Fluticasone", "25/50 µg", "Aérosol dosé", "Combinaison bronchodilatateur-corticoïde"),
    ("Sérétide", "Salmétérol-Fluticasone", "25/125 µg", "Aérosol dosé", "Combinaison bronchodilatateur-corticoïde"),
    ("Sérétide", "Salmétérol-Fluticasone", "25/250 µg", "Aérosol dosé", "Combinaison bronchodilatateur-corticoïde"),
    ("Sérétide Diskus", "Salmétérol-Fluticasone", "50/100 µg", "Poudre inhalée", "Combinaison bronchodilatateur-corticoïde"),
    ("Sérétide Diskus", "Salmétérol-Fluticasone", "50/250 µg", "Poudre inhalée", "Combinaison bronchodilatateur-corticoïde"),
    ("Atrovent", "Ipratropium", "20 µg/dose", "Aérosol dosé", "Anticholinergique inhalé"),
    ("Atrovent", "Ipratropium", "500 µg/2 ml", "Nébulisation", "Anticholinergique inhalé"),
    ("Singulair", "Montélukast", "10 mg", "Comprimé pelliculé", "Antileucotriène"),
    ("Singulair", "Montélukast", "4 mg", "Granulés", "Antileucotriène"),
    ("Prednisone", "Prednisone", "20 mg", "Comprimé", "Corticoïde oral"),
    ("Prednisone", "Prednisone", "5 mg", "Comprimé", "Corticoïde oral"),
    ("Déxaméthasone", "Déxaméthasone", "0,75 mg", "Comprimé", "Corticoïde oral"),
    ("Déxaméthasone", "Déxaméthasone", "4 mg/ml", "Solution injectable", "Corticoïde injectable"),
    ("Solulab", "Acétylcystéine", "600 mg", "Granulés", "Mucolytique"),
    ("Fluimucil", "Acétylcystéine", "200 mg", "Granulés", "Mucolytique"),
    ("Mucosolvan", "Ambroxol", "30 mg", "Comprimé", "Mucolytique"),
    ("Mucosolvan", "Ambroxol", "15 mg/5 ml", "Sirop", "Mucolytique"),

    # ── CONTRACEPTIFS ──
    ("Microgynon", "Éthinylestradiol-Lévonorgestrel", "30/150 µg", "Comprimé", "Contraceptif oral combiné"),
    ("Diane 35", "Éthinylestradiol-Cyproterone", "35/2 mg", "Comprimé", "Contraceptif oral combiné"),
    ("Valinea", "Éthinylestradiol-Lévonorgestrel", "30/150 µg", "Comprimé", "Contraceptif oral combiné"),
    ("Ovranette", "Éthinylestradiol-Lévonorgestrel", "30/150 µg", "Comprimé", "Contraceptif oral combiné"),
    ("Leeloo", "Éthinylestradiol-Lévonorgestrel", "30/150 µg", "Comprimé", "Contraceptif oral combiné"),
    ("Desogrel", "Desogestrel", "75 µg", "Comprimé", "Contraceptif oral progestatif"),
    ("Cerazette", "Desogestrel", "75 µg", "Comprimé", "Contraceptif oral progestatif"),
    ("Depo-Provera", "Acétate de médroxyprogestérone", "150 mg/ml", "Solution injectable", "Contraceptif injectable"),
    ("Noristerat", "Enanthate de norethistérone", "200 mg/ml", "Solution injectable", "Contraceptif injectable"),
    ("Progestérone", "Micronisé de progestérone", "200 mg", "Gélule", "Progestatif"),
    ("Duphaston", "Dydrogestérone", "10 mg", "Comprimé", "Progestatif"),
    ("Luteran", "Acétate de chlormadinone", "2,5 mg", "Comprimé", "Progestatif"),
    ("Noriday", "Norethistérone", "350 µg", "Comprimé", "Contraceptif oral progestatif"),
    ("Stediril", "Éthinylestradiol-Lévonorgestrel", "30/150 µg", "Comprimé", "Contraceptif oral combiné"),

    # ── VITAMINES / COMPLÉMENTS ──
    ("Davitamon", "Multivitamines", "Complexe", "Comprimé", "Vitamine"),
    ("Supradyn", "Multivitamines-Minéraux", "Complexe", "Comprimé effervescent", "Vitamine"),
    ("Calmag", "Calcium-Magnésium", "600/40 mg", "Comprimé", "Complément minéral"),
    ("Vitamine C Roche", "Acide ascorbique", "1 g", "Comprimé effervescent", "Vitamine"),
    ("Vitamine C UPSA", "Acide ascorbique", "750 mg", "Comprimé effervescent", "Vitamine"),
    ("Vitamine D3", "Cholécalciférol", "100 000 UI", "Solution injectable", "Vitamine"),
    ("Vitamine D3", "Cholécalciférol", "800 UI", "Comprimé", "Vitamine"),
    ("Acide folique", "Acide folique", "5 mg", "Comprimé", "Vitamine"),
    ("Acide folique", "Acide folique", "0,4 mg", "Comprimé", "Vitamine"),
    ("Ferrograd", "Fer fumarate", "325 mg", "Comprimé", "Complément martiale"),
    ("Tardyferon", "Fer sulfurique", "80 mg", "Comprimé", "Complément martiale"),
    ("Gestabis", "Fer-Acide folique-Folicule", "Complexe", "Gélule", "Complément martiale"),
    ("Fer-Os", "Fer polypeptidique", "40 mg", "Comprimé", "Complément martiale"),
    ("Zinc", "Zinc", "20 mg", "Comprimé", "Complément minéral"),
    ("Selenium", "Sélénium", "100 µg", "Gélule", "Complément minéral"),
    ("Magné B6", "Magnésium-Pyridoxine", "150/20 mg", "Comprimé", "Complément minéral"),
    ("Magné B6", "Magnésium-Pyridoxine", "100 mg/10 mg", "Solution buvable", "Complément minéral"),
    ("Vitamine B Complex", "Vitamines B", "Complexe", "Comprimé", "Vitamine"),
    ("Poly-Lectherb", "Fer-Acide folique-B12", "Complexe", "Sirop", "Complément martiale"),
    ("Mumfer", "Fer-Acide folique", "Complexe", "Sirop", "Complément martiale"),

    # ── ANTIFONGIQUES ──
    ("Fluconazole", "Fluconazole", "150 mg", "Gélule", "Antifongique"),
    ("Fluconazole", "Fluconazole", "200 mg", "Comprimé", "Antifongique"),
    ("Nystatine", "Nystatine", "500 000 UI", "Comprimé", "Antifongique"),
    ("Nystatine", "Nystatine", "100 000 UI/ml", "Suspension buccale", "Antifongique"),
    ("Miconazole", "Miconazole", "2%", "Crème", "Antifongique"),
    ("Daktarin", "Miconazole", "2%", "Gel buccal", "Antifongique"),
    ("Kétoconazole", "Kétoconazole", "200 mg", "Comprimé", "Antifongique"),
    ("Kétoconazole", "Kétoconazole", "2%", "Shampoing", "Antifongique"),
    ("Terbinafine", "Terbinafine", "250 mg", "Comprimé", "Antifongique"),
    ("Terbinafine", "Terbinafine", "1%", "Crème", "Antifongique"),

    # ── ANTIPARASITAIRES / ANTIVIRUS ──
    ("Vermox", "Mébendazole", "100 mg", "Comprimé", "Antiparasitaire"),
    ("Vermox", "Mébendazole", "500 mg", "Comprimé", "Antiparasitaire"),
    ("Albendazole", "Albendazole", "400 mg", "Comprimé", "Antiparasitaire"),
    ("Albendazole", "Albendazole", "200 mg", "Suspension buvable", "Antiparasitaire"),
    ("Stromectol", "Ivermectine", "3 mg", "Comprimé", "Antiparasitaire"),
    ("Metronidazole suspension", "Métrodinazole", "200 mg/5 ml", "Suspension buvable", "Antiparasitaire"),
    ("Praziquantel", "Praziquantel", "600 mg", "Comprimé", "Antiparasitaire"),
    ("Niclosamide", "Niclosamide", "500 mg", "Comprimé", "Antiparasitaire"),
    ("Acyclovir", "Acyclovir", "200 mg", "Comprimé", "Antiviral"),
    ("Acyclovir", "Acyclovir", "500 mg", "Comprimé", "Antiviral"),
    ("Acyclovir", "Acyclovir", "5%", "Pommade", "Antiviral"),
    ("Valacyclovir", "Valaciclovir", "500 mg", "Comprimé pelliculé", "Antiviral"),

    # ── GASTRO-ENTÉROLOGIE ──
    ("Maalox", "Hydroxyde d'aluminium-Magnésium", "250/250 mg", "Comprimé", "Antiacide"),
    ("Maalox", "Hydroxyde d'aluminium-Magnésium", "250/250 mg", "Suspension buvable", "Antiacide"),
    ("Gaviscon", "Alginates de sodium", "500 mg", "Comprimé", "Antiacide"),
    ("Gaviscon", "Alginates de sodium", "10 mg/ml", "Suspension buvable", "Antiacide"),
    ("Omeprazole", "Omeprazole", "20 mg", "Gélule", "Inhibiteur de la pompe à protons"),
    ("Omeprazole", "Omeprazole", "40 mg", "Gélule", "Inhibiteur de la pompe à protons"),
    ("Losec", "Omeprazole", "20 mg", "Gélule", "Inhibiteur de la pompe à protons"),
    ("Lansoprazole", "Lansoprazole", "30 mg", "Gélule", "Inhibiteur de la pompe à protons"),
    ("Lansoprazole", "Lansoprazole", "15 mg", "Gélule", "Inhibiteur de la pompe à protons"),
    ("Motilium", "Dompéridone", "10 mg", "Comprimé", "Prokinétique"),
    ("Motilium", "Dompéridone", "30 mg/5 ml", "Sirop", "Prokinétique"),
    ("Imodium", "Lopéramide", "2 mg", "Gélule", "Antidiarrhéique"),
    ("Smecta", "Diosmectite", "3 g", "Poudre", "Antidiarrhéique"),
    ("Enterogermina", "Bacillus clausii", "2 milliards", "Suspension buvable", "Probiotique"),
    ("Spasfon", "Phloroglucinol", "80 mg", "Comprimé", "Antispasmodique"),
    ("Spasfon", "Phloroglucinol", "40 mg/4 ml", "Solution injectable", "Antispasmodique"),
    ("Dulcolax", "Bisacodyl", "5 mg", "Comprimé", "Laxatif"),
    ("Forlax", "Macrogol", "10 g", "Poudre", "Laxatif"),

    # ── DERMATOLOGIE ──
    ("Béthanechol", "Acétylcholine", "2,5%", "Pommade", "Dermatologie"),
    ("Diprosone", "Bétaméthasone", "0,05%", "Crème", "Corticoïde dermatologique"),
    ("Diprosone", "Bétaméthasone", "0,05%", "Lotion", "Corticoïde dermatologique"),
    ("Elocom", "Mométasone", "0,1%", "Crème", "Corticoïde dermatologique"),
    ("Elocom", "Mométasone", "0,1%", "Pommade", "Corticoïde dermatologique"),
    ("Hydrocortisone", "Hydrocortisone", "1%", "Crème", "Corticoïde dermatologique"),
    ("Hydrocortisone", "Hydrocortisone", "0,5%", "Pommade", "Corticoïde dermatologique"),
    ("Stéroid", "Bétaméthasone-Clotrimazole", "0,05/1%", "Crème", "Corticoïde antifongique"),
    ("Bepanthen", "Dexpanthénol", "5%", "Crème", "Cicatrisant"),
    ("Cicabio", "Cicabio", "Complexe", "Crème", "Cicatrisant"),
    ("Fucicort", "Acide fusidique-Bétaméthasone", "2%/0,1%", "Crème", "Antibiotique-corticoïde"),
    ("Fucidine", "Acide fusidique", "2%", "Crème", "Antibiotique topique"),
    ("Fucidine", "Acide fusidique", "2%", "Pommade", "Antibiotique topique"),
    ("Bactroban", "Mupirocine", "2%", "Pommade", "Antibiotique topique"),
    ("Crotamiton", "Crotamiton", "10%", "Crème", "Antiparasitaire topique"),
    ("Scabicide", "Péréméthrine", "5%", "Crème", "Antiparasitaire topique"),

    # ── CARDIOLOGIE / HÉMATOLOGIE ──
    ("Plavix", "Clopidogrel", "75 mg", "Comprimé pelliculé", "Antiagrégant plaquettaire"),
    ("Plavix", "Clopidogrel", "300 mg", "Comprimé pelliculé", "Antiagrégant plaquettaire"),
    ("Sintrom", "Acénocoumarol", "4 mg", "Comprimé", "Anticoagulant"),
    ("Coumadine", "Warfarine", "2,5 mg", "Comprimé", "Anticoagulant"),
    ("Coumadine", "Warfarine", "5 mg", "Comprimé", "Anticoagulant"),
    ("Héparine", "Héparine sodique", "5 000 UI/0,5 ml", "Solution injectable", "Anticoagulant"),
    ("Lovenox", "Énoxaparine sodique", "4 000 UI/0,4 ml", "Solution injectable", "Anticoagulant"),
    ("Lovenox", "Énoxaparine sodique", "6 000 UI/0,6 ml", "Solution injectable", "Anticoagulant"),
    ("Cordarone", "Amiodarone", "200 mg", "Comprimé", "Antiarythmique"),
    ("Digoxine", "Digoxine", "0,25 mg", "Comprimé", "Cardiotonique"),
    ("Digoxine", "Digoxine", "0,5 mg/2 ml", "Solution injectable", "Cardiotonique"),

    # ── NEUROLOGIE / PSYCHIATRIE ──
    ("Diazépam", "Diazépam", "5 mg", "Comprimé", "Benzodiazépine"),
    ("Diazépam", "Diazépam", "10 mg", "Comprimé", "Benzodiazépine"),
    ("Valium", "Diazépam", "10 mg", "Comprimé", "Benzodiazépine"),
    ("Rivotril", "Clonazépam", "2 mg", "Comprimé", "Benzodiazépine"),
    ("Rivotril", "Clonazépam", "0,5 mg", "Gouttes", "Benzodiazépine"),
    ("Lorazépam", "Lorazépam", "1 mg", "Comprimé", "Benzodiazépine"),
    ("Lorazépam", "Lorazépam", "2,5 mg/ml", "Solution injectable", "Benzodiazépine"),
    ("Phénobarbital", "Phénobarbital", "100 mg", "Comprimé", "Anticonvulsivant"),
    ("Phénobarbital", "Phénobarbital", "200 mg/ml", "Solution injectable", "Anticonvulsivant"),
    ("Carbamazépine", "Carbamazépine", "200 mg", "Comprimé", "Anticonvulsivant"),
    ("Carbamazépine", "Carbamazépine", "400 mg", "Comprimé", "Anticonvulsivant"),
    ("Tegretol", "Carbamazépine", "200 mg", "Comprimé", "Anticonvulsivant"),
    ("Dilantin", "Phénytoïne", "100 mg", "Gélule", "Anticonvulsivant"),
    ("Éthosuximide", "Éthosuximide", "250 mg", "Gélule", "Anticonvulsivant"),
    ("Acide valproïque", "Acide valproïque", "500 mg", "Comprimé", "Anticonvulsivant"),
    ("Dépakine", "Acide valproïque", "500 mg", "Comprimé", "Anticonvulsivant"),
    ("Dépakine", "Acide valproïque", "200 mg/5 ml", "Sirop", "Anticonvulsivant"),
    ("Amitriptyline", "Amitriptyline", "25 mg", "Comprimé", "Antidépresseur"),
    ("Amitriptyline", "Amitriptyline", "50 mg", "Comprimé", "Antidépresseur"),
    ("Fluoxétine", "Fluoxétine", "20 mg", "Gélule", "Antidépresseur ISRS"),
    ("Prozac", "Fluoxétine", "20 mg", "Gélule", "Antidépresseur ISRS"),
    ("Sertraline", "Sertraline", "50 mg", "Comprimé pelliculé", "Antidépresseur ISRS"),
    ("Sertraline", "Sertraline", "100 mg", "Comprimé pelliculé", "Antidépresseur ISRS"),
    ("Escitalopram", "Escitalopram", "10 mg", "Comprimé pelliculé", "Antidépresseur ISRS"),
    ("Escitalopram", "Escitalopram", "20 mg", "Comprimé pelliculé", "Antidépresseur ISRS"),
    ("Clomipramine", "Clomipramine", "25 mg", "Gélule", "Antidépresseur"),
    ("Clomipramine", "Clomipramine", "50 mg", "Gélule", "Antidépresseur"),
    ("Imovane", "Zopiclone", "7,5 mg", "Comprimé pelliculé", "Hypnotique"),
    ("Stilnox", "Zolpidem", "10 mg", "Comprimé pelliculé", "Hypnotique"),

    # ── HORMONOTHÉRAPIE / ENDOCRINOLOGIE ──
    ("Lévothyrox", "Lévothyroxine sodique", "50 µg", "Comprimé", "Hormone thyroïdienne"),
    ("Lévothyrox", "Lévothyroxine sodique", "75 µg", "Comprimé", "Hormone thyroïdienne"),
    ("Lévothyrox", "Lévothyroxine sodique", "100 µg", "Comprimé", "Hormone thyroïdienne"),
    ("Lévothyrox", "Lévothyroxine sodique", "125 µg", "Comprimé", "Hormone thyroïdienne"),
    ("Lévothyrox", "Lévothyroxine sodique", "150 µg", "Comprimé", "Hormone thyroïdienne"),
    ("Euthyral", "Lévothyroxine sodique", "100 µg", "Comprimé", "Hormone thyroïdienne"),
    ("Cytomel", "Liothyronine", "20 µg", "Comprimé", "Hormone thyroïdienne"),
    ("Tamoxifène", "Tamoxifène", "20 mg", "Comprimé pelliculé", "Anti-œstrogène"),
    ("Clomifène", "Clomifène", "50 mg", "Comprimé", "Stimulant ovulatoire"),

    # ── UROLOGIE ──
    ("Tamsulosine", "Tamsulosine", "0,4 mg", "Gélule", "Alpha-bloquant"),
    ("Omnic", "Tamsulosine", "0,4 mg", "Gélule", "Alpha-bloquant"),
    ("Finastéride", "Finastéride", "5 mg", "Comprimé pelliculé", "Inhibiteur 5-alpha-réductase"),
    ("Propecia", "Finastéride", "1 mg", "Comprimé pelliculé", "Inhibiteur 5-alpha-réductase"),
    ("Detrusitol", "Tolterodine", "2 mg", "Comprimé pelliculé", "Antispasmodique vésical"),

    # ── OPHTALMOLOGIE ──
    ("Timolol", "Timolol", "0,25%", "Collyre", "Bêta-bloquant ophtalmique"),
    ("Timolol", "Timolol", "0,50%", "Collyre", "Bêta-bloquant ophtalmique"),
    ("Latanoprost", "Latanoprost", "0,005%", "Collyre", "Prostaglandine ophtalmique"),
    ("Xalatan", "Latanoprost", "0,005%", "Collyre", "Prostaglandine ophtalmique"),
    ("Tobramycine", "Tobramycine", "0,3%", "Collyre", "Antibiotique ophtalmique"),
    ("Chloramphénicol", "Chloramphénicol", "0,5%", "Collyre", "Antibiotique ophtalmique"),

    # ── AUTRES SPÉCIALITÉS ──
    ("Metoclopramide", "Métoclopramide", "10 mg", "Comprimé", "Antiemétique"),
    ("Metoclopramide", "Métoclopramide", "10 mg/2 ml", "Solution injectable", "Antiemétique"),
    ("Plasil", "Métoclopramide", "10 mg", "Comprimé", "Antiemétique"),
    ("Primperan", "Métoclopramide", "10 mg/2 ml", "Solution injectable", "Antiemétique"),
    ("Ondansétron", "Ondansétron", "4 mg", "Comprimé pelliculé", "Antiemétique"),
    ("Ondansétron", "Ondansétron", "4 mg/2 ml", "Solution injectable", "Antiemétique"),
    ("Cotrimoxazole Fort", "Sulfaméthoxazole-Triméthoprime", "800/160 mg", "Comprimé", "Antibiotique"),
    ("Ranitidine", "Ranitidine", "150 mg", "Comprimé", "Antihistaminique H2"),
    ("Ranitidine", "Ranitidine", "300 mg", "Comprimé", "Antihistaminique H2"),
    ("Cimetidine", "Cimétidine", "200 mg", "Comprimé", "Antihistaminique H2"),
    ("Telfast", "Fexofénadine", "120 mg", "Comprimé pelliculé", "Antihistaminique"),
    ("Telfast", "Fexofénadine", "180 mg", "Comprimé pelliculé", "Antihistaminique"),
    ("Zyrtec", "Cétirizine", "10 mg", "Comprimé pelliculé", "Antihistaminique"),
    ("Zyrtec", "Cétirizine", "10 mg/ml", "Gouttes", "Antihistaminique"),
    ("Loratadine", "Loratadine", "10 mg", "Comprimé pelliculé", "Antihistaminique"),
    ("Phenergan", "Prométhazine", "25 mg", "Comprimé", "Antihistaminique"),
    ("Phenergan", "Prométhazine", "50 mg/2 ml", "Solution injectable", "Antihistaminique"),
    ("Suprastin", "Chloropyramine", "25 mg", "Comprimé", "Antihistaminique"),
    ("Bétahistine", "Bétahistine", "16 mg", "Comprimé", "Antivertigineux"),
    ("Bétahistine", "Bétahistine", "24 mg", "Comprimé", "Antivertigineux"),
    ("Cinnarizine", "Cinnarizine", "25 mg", "Comprimé", "Antivertigineux"),
]


def seed():
    engine = create_engine(DATABASE_URL)
    with engine.begin() as conn:
        count = conn.execute(text("SELECT COUNT(*) FROM medicaments")).scalar()
        if count >= len(MEDICAMENTS):
            print(f"La table contient déjà {count} médicaments. Rien à faire.")
            return

        insert_stmt = text("""
            INSERT INTO medicaments (nom_commercial, dci, dosage, forme, classe_therapeutique)
            VALUES (:nom_commercial, :dci, :dosage, :forme, :classe_therapeutique)
        """)

        for nom_commercial, dci, dosage, forme, classe in MEDICAMENTS:
            conn.execute(insert_stmt, {
                "nom_commercial": nom_commercial,
                "dci": dci,
                "dosage": dosage,
                "forme": forme,
                "classe_therapeutique": classe,
            })

        print(f"{len(MEDICAMENTS)} médicaments insérés avec succès.")


if __name__ == "__main__":
    seed()
