    import { jsPDF } from "jspdf";
    import autoTable from "jspdf-autotable";

    export function exportToPdf(data = {}) {
    const doc = new jsPDF();

    /* ================= HEADER ================= */
    doc.setFontSize(18);
    doc.text("Health Observatory Report", 14, 20);

    doc.setFontSize(11);
    doc.text("National Medical Analytics System (NERE HEALTH)", 14, 28);

    doc.setLineWidth(0.5);
    doc.line(14, 32, 196, 32);

    /* ================= META INFO ================= */
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 40);
    doc.text("Confidential Report - Government / NGO Use Only", 14, 46);

    /* ================= KPI SECTION ================= */
    autoTable(doc, {
        startY: 55,
        head: [["Indicator", "Value"]],
        body: [
        ["Total Patients", data.totalPatients || "1,200,000"],
        ["Active Diseases", data.activeDiseases || "24"],
        ["Critical Cases", data.criticalCases || "3,450"],
        ["Vaccination Rate", data.vaccinationRate || "78%"],
        ],
        theme: "grid",
        headStyles: { fillColor: [37, 99, 235] },
    });

    /* ================= EPIDEMIC DATA ================= */
    autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 10,
        head: [["Region", "Cases", "Risk Level"]],
        body: [
        ["Littoral", "12,000", "High"],
        ["Centre", "9,500", "Medium"],
        ["Nord", "4,200", "Low"],
        ["Ouest", "3,100", "Low"],
        ],
        theme: "striped",
        headStyles: { fillColor: [16, 185, 129] },
    });

    /* ================= DISEASE DISTRIBUTION ================= */
    autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 10,
        head: [["Disease", "Cases"]],
        body: [
        ["Malaria", "400,000"],
        ["Typhoid", "250,000"],
        ["Cholera", "80,000"],
        ["Flu", "150,000"],
        ],
    });

    /* ================= FOOTER ================= */
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(9);
    doc.text(
        "Generated by NERE HEALTH Observatory System - Confidential",
        14,
        pageHeight - 10
    );

    /* ================= SAVE ================= */
    doc.save("health-observatory-report.pdf");
    }