export const appointments = [
  {
    id: 1,
    patientName: "Emma Johnson",
    patientImage: "https://randomuser.me/api/portraits/women/44.jpg",
    status: "Confirmed",
    date: "12 Apr 2026",
    time: "10:30 AM",
    type: "Teleconsultation",
    category: "past",
  },
  {
    id: 2,
    patientName: "Daniel Smith",
    patientImage: "https://randomuser.me/api/portraits/men/32.jpg",
    status: "Pending",
    date: "13 may 2026",
    time: "02:00 PM",
    type: "In-person",
  },
  {
    id: 3,
    patientName: "Sophia Brown",
    patientImage: "https://randomuser.me/api/portraits/women/65.jpg",
    status: "Cancelled",
    date: "14 Apr 2026",
    time: "09:15 AM",
    type: "Teleconsultation",
    category: "upcoming",
  },
   {
    id: 4,
    patientName: "Emma Johnson",
    patientImage: "https://randomuser.me/api/portraits/women/44.jpg",
    status: "Confirmed",
    date: "12 Apr 2026",
    time: "10:30 AM",
    type: "Teleconsultation",
    category: "past"
  },
  {
    id: 5,
    patientName: "Daniel Smith",
    patientImage: "https://randomuser.me/api/portraits/men/32.jpg",
    status: "Pending",
    date: "13 Apr 2026",
    time: "02:00 PM",
    type: "In-person",
    category: "upcoming",
  },
  {
    id: 6,
    patientName: "Sophia Brown",
    patientImage: "https://randomuser.me/api/portraits/women/65.jpg",
    status: "Cancelled",
    date: "14 Apr 2026",
    time: "09:15 AM",
    type: "Teleconsultation",
    category: "upcoming"
  },
];