"""initial schema for tests
Revision ID: 854a93350b2e
Revises: 0001_initial
Create Date: 2026-04-16 09:44:56.926341
"""

from alembic import op
import sqlalchemy as sa

revision = '854a93350b2e'
down_revision = '0001_initial'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialites',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('libelle_fr', sa.String(length=150), nullable=False),
    sa.Column('libelle_en', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icone_url', sa.String(length=1000), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('ordre_affichage', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('patient', 'medecin', 'structure', 'admin', 'observateur', name='role_utilisateur'), nullable=False),
    sa.Column('statut', postgresql.ENUM('actif', 'inactif', 'suspendu', 'en_attente', 'supprime', name='statut_compte'), server_default=sa.text("'en_attente'::public.statut_compte"), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('langue', sa.String(length=5), server_default=sa.text("'fr'"), nullable=False),
    sa.Column('theme', postgresql.ENUM('clair', 'sombre', 'auto', name='theme_interface'), server_default=sa.text("'clair'::public.theme_interface"), nullable=False),
    sa.Column('totp_secret', sa.String(length=100), nullable=True),
    sa.Column('totp_actif', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_verifie', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_otp', sa.String(length=6), nullable=True),
    sa.Column('email_otp_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telephone_verifie', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nb_tentatives_connexion', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bloque_jusqu_a', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('telephone', name='uq_users_telephone')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('rappel_rdv', 'confirmation_rdv', 'annulation_rdv', 'confirmation_paiement', 'echec_paiement', 'remboursement', 'nouveau_message', 'resultat_labo_disponible', 'ordonnance_prete', 'alerte_systeme', 'compte_valide', 'compte_rejete', 'nouveaux_avis', name='type_notification'), nullable=False),
    sa.Column('canal', postgresql.ENUM('push', 'sms', 'email', 'in_app', 'whatsapp', name='canal_notification'), server_default=sa.text("'in_app'::public.canal_notification"), nullable=False),
    sa.Column('statut', postgresql.ENUM('en_attente', 'envoye', 'lu', 'echoue', 'expire', name='statut_notification'), server_default=sa.text("'en_attente'::public.statut_notification"), nullable=False),
    sa.Column('titre', sa.String(length=300), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('donnees_supplementaires', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('date_envoi_planifie', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_envoi_reel', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_lecture', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nb_tentatives', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('derniere_erreur', sa.Text(), nullable=True),
    sa.Column('prochaine_tentative', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_externe', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_statut', 'notifications', ['statut'], unique=False)
    op.create_index('ix_notifications_utilisateur_id', 'notifications', ['utilisateur_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('numero_patient', sa.String(length=25), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('sexe', postgresql.ENUM('M', 'F', 'Autre', 'Non_precise', name='sexe_enum'), server_default=sa.text("'Non_precise'::public.sexe_enum"), nullable=False),
    sa.Column('groupe_sanguin', postgresql.ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Inconnu', name='groupe_sanguin_enum'), server_default=sa.text("'Inconnu'::public.groupe_sanguin_enum"), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=50), server_default=sa.text("'CM'"), nullable=False),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('taille_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('poids_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('allergies', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('antecedents_medicaux', sa.Text(), nullable=True),
    sa.Column('medicaments_en_cours', sa.Text(), nullable=True),
    sa.Column('couverture_assurance', sa.String(length=200), nullable=True),
    sa.Column('numero_assurance', sa.String(length=100), nullable=True),
    sa.Column('organisme_assurance', sa.String(length=200), nullable=True),
    sa.Column('contact_urgence_nom', sa.String(length=150), nullable=True),
    sa.Column('contact_urgence_tel', sa.String(length=20), nullable=True),
    sa.Column('contact_urgence_lien', sa.String(length=50), nullable=True),
    sa.Column('consentement_donnees', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_consentement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consentement_marketing', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_patient', name='uq_patients_numero_patient')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('access_token_jti', sa.String(length=100), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('appareil', sa.String(length=200), nullable=True),
    sa.Column('localisation', sa.String(length=200), nullable=True),
    sa.Column('plateforme', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoque', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_revocation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motif_revocation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom_etablissement', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('statut_verification', postgresql.ENUM('en_attente', 'en_cours_verification', 'verifie', 'rejete', 'suspendu', name='statut_verification'), server_default=sa.text("'en_attente'::public.statut_verification"), nullable=False),
    sa.Column('numero_autorisation', sa.String(length=100), nullable=True),
    sa.Column('numero_contribuable', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=50), server_default=sa.text("'CM'"), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('telephone_pro', sa.String(length=20), nullable=True),
    sa.Column('email_pro', sa.String(length=255), nullable=True),
    sa.Column('site_web', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.Column('horaires_ouverture', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('services_offerts', sa.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::text[]'), nullable=False),
    sa.Column('capacite_lits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=True),
    sa.Column('role_utilisateur', postgresql.ENUM('patient', 'medecin', 'structure', 'admin', 'observateur', name='role_utilisateur'), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('action', postgresql.ENUM('creation', 'lecture', 'modification', 'suppression', 'connexion', 'deconnexion', 'tentative_connexion_echec', 'paiement_initie', 'paiement_confirme', 'paiement_echoue', 'remboursement', 'export_donnees', 'acces_dossier_medical', 'acces_ordonnance', 'validation_compte', 'suspension_compte', 'revocation_session', 'upload_document', 'teleconsultation_debut', 'teleconsultation_fin', name='action_audit'), nullable=False),
    sa.Column('entite_type', sa.String(length=100), nullable=True),
    sa.Column('entite_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('methode_http', sa.String(length=10), nullable=True),
    sa.Column('donnees_avant', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('donnees_apres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('succes', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('code_http', sa.SmallInteger(), nullable=True),
    sa.Column('message_erreur', sa.Text(), nullable=True),
    sa.Column('duree_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medecins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_ordre', sa.String(length=60), nullable=False),
    sa.Column('statut_verification', postgresql.ENUM('en_attente', 'en_cours_verification', 'verifie', 'rejete', 'suspendu', name='statut_verification'), server_default=sa.text("'en_attente'::public.statut_verification"), nullable=False),
    sa.Column('date_verification', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verifie_par_admin_id', sa.UUID(), nullable=True),
    sa.Column('annees_experience', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('biographie', sa.Text(), nullable=True),
    sa.Column('diplomes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('langues_parlees', sa.ARRAY(sa.String(length=10)), server_default=sa.text("ARRAY['fr'::text]"), nullable=False),
    sa.Column('tarif_consultation', sa.Numeric(precision=10, scale=2), server_default=sa.text('5000.00'), nullable=False),
    sa.Column('devise', postgresql.ENUM('XAF', 'EUR', 'USD', 'GBP', 'XOF', name='devise_enum'), server_default=sa.text("'XAF'::public.devise_enum"), nullable=False),
    sa.Column('teleconsultation_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('note_moyenne', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('nombre_avis', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('nombre_consultations', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=True),
    sa.Column('disponible_maintenant', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.ForeignKeyConstraint(['verifie_par_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disponibilites',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('jour_semaine', postgresql.ENUM('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche', name='jour_semaine'), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('duree_creneau_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('type', postgresql.ENUM('presentiel', 'video', 'audio', 'chat', name='type_consultation'), server_default=sa.text("'video'::public.type_consultation"), nullable=False),
    sa.Column('recurrence', postgresql.ENUM('unique', 'quotidien', 'hebdomadaire', 'bi_mensuel', 'mensuel', name='recurrence_enum'), server_default=sa.text("'hebdomadaire'::public.recurrence_enum"), nullable=False),
    sa.Column('date_debut_validite', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('date_fin_validite', sa.Date(), nullable=True),
    sa.Column('exceptions', sa.ARRAY(sa.Date()), server_default=sa.text('ARRAY[]::date[]'), nullable=False),
    sa.Column('actif', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossiers_medicaux',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('numero_dossier', sa.String(length=30), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medecin_traitant_id', sa.UUID(), nullable=True),
    sa.Column('antecedents_familiaux', sa.Text(), nullable=True),
    sa.Column('antecedents_personnels', sa.Text(), nullable=True),
    sa.Column('antecedents_chirurgicaux', sa.Text(), nullable=True),
    sa.Column('antecedents_allergiques', sa.Text(), nullable=True),
    sa.Column('antecedents_gyneco', sa.Text(), nullable=True),
    sa.Column('habitudes_vie', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('taille_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('poids_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('imc', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tension_arterielle', sa.String(length=20), nullable=True),
    sa.Column('glycemie_a_jeun', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vaccinations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('traitements_chroniques', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('code_partage', sa.String(length=20), nullable=True),
    sa.Column('code_partage_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_traitant_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_partage', name='uq_dossiers_medicaux_code_partage'),
    sa.UniqueConstraint('numero_dossier', name='uq_dossiers_medicaux_numero_dossier'),
    sa.UniqueConstraint('patient_id', name='uq_dossiers_medicaux_patient_id')
    )
    op.create_index('ix_dossiers_medicaux_medecin_traitant_id', 'dossiers_medicaux', ['medecin_traitant_id'], unique=False)
    op.create_table('medecin_specialites',
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('specialite_id', sa.UUID(), nullable=False),
    sa.Column('principale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('annees_pratique', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('certifie', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('annees_pratique >= 0', name='medecin_specialites_annees_pratique_check'),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['specialite_id'], ['specialites.id'], ),
    sa.PrimaryKeyConstraint('medecin_id', 'specialite_id', name='pk_medecin_specialites')
    )
    op.create_table('rendez_vous',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('numero_rdv', sa.String(length=30), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=True),
    sa.Column('date_heure_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_heure_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', postgresql.ENUM('presentiel', 'video', 'audio', 'chat', name='type_consultation'), nullable=False),
    sa.Column('statut', postgresql.ENUM('en_attente', 'confirme', 'annule_patient', 'annule_medecin', 'annule_systeme', 'en_cours', 'termine', 'no_show_patient', 'no_show_medecin', 'rembourse', name='statut_rdv'), server_default=sa.text("'en_attente'::public.statut_rdv"), nullable=False),
    sa.Column('motif_consultation', sa.Text(), nullable=True),
    sa.Column('symptomes_declares', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('notes_patient', sa.Text(), nullable=True),
    sa.Column('notes_pre_consultation', sa.Text(), nullable=True),
    sa.Column('lien_video', sa.String(length=1000), nullable=True),
    sa.Column('webrtc_room_id', sa.String(length=100), nullable=True),
    sa.Column('token_patient', sa.String(length=500), nullable=True),
    sa.Column('token_medecin', sa.String(length=500), nullable=True),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('devise', postgresql.ENUM('XAF', 'EUR', 'USD', 'GBP', 'XOF', name='devise_enum'), server_default=sa.text("'XAF'::public.devise_enum"), nullable=False),
    sa.Column('annule_par', sa.UUID(), nullable=True),
    sa.Column('motif_annulation', sa.Text(), nullable=True),
    sa.Column('date_annulation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rappel_j1_envoye', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rappel_h1_envoye', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note_patient', sa.SmallInteger(), nullable=True),
    sa.Column('commentaire_patient', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annule_par'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_rdv', name='uq_rendez_vous_numero_rdv')
    )
    op.create_index('ix_rendez_vous_date_heure_debut', 'rendez_vous', ['date_heure_debut'], unique=False)
    op.create_index('ix_rendez_vous_medecin_id', 'rendez_vous', ['medecin_id'], unique=False)
    op.create_index('ix_rendez_vous_patient_id', 'rendez_vous', ['patient_id'], unique=False)
    op.create_index('ix_rendez_vous_structure_id', 'rendez_vous', ['structure_id'], unique=False)
    op.create_table('avis',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('rdv_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.SmallInteger(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('verifie', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verifie_par', sa.UUID(), nullable=True),
    sa.Column('masque', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('motif_masquage', sa.Text(), nullable=True),
    sa.Column('reponse_medecin', sa.Text(), nullable=True),
    sa.Column('date_reponse', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['rdv_id'], ['rendez_vous.id'], ),
    sa.ForeignKeyConstraint(['verifie_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_avis_medecin_id', 'avis', ['medecin_id'], unique=False)
    op.create_index('ix_avis_patient_id', 'avis', ['patient_id'], unique=False)
    op.create_index('ix_avis_rdv_id', 'avis', ['rdv_id'], unique=False)
    op.create_table('chatbot_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('symptomes_detectes', sa.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::text[]'), nullable=False),
    sa.Column('specialite_suggeree', sa.String(length=100), nullable=True),
    sa.Column('niveau_urgence', postgresql.ENUM('faible', 'modere', 'eleve', 'urgence_vitale', name='niveau_urgence'), server_default=sa.text("'faible'::public.niveau_urgence"), nullable=False),
    sa.Column('redirection_rdv', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rdv_cree_id', sa.UUID(), nullable=True),
    sa.Column('modele_ia', sa.String(length=50), server_default=sa.text("'gpt-4o-mini'"), nullable=False),
    sa.Column('tokens_utilises', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cout_estime_usd', sa.Numeric(precision=10, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('statut', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['rdv_cree_id'], ['rendez_vous.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatbot_sessions_medecin_id', 'chatbot_sessions', ['medecin_id'], unique=False)
    op.create_index('ix_chatbot_sessions_patient_id', 'chatbot_sessions', ['patient_id'], unique=False)
    op.create_index('ix_chatbot_sessions_rdv_cree_id', 'chatbot_sessions', ['rdv_cree_id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('numero_consultation', sa.String(length=30), nullable=False),
    sa.Column('rdv_id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('date_heure_debut', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_heure_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('anamnese', sa.Text(), nullable=True),
    sa.Column('examen_clinique', sa.Text(), nullable=True),
    sa.Column('diagnostic_principal', sa.Text(), nullable=True),
    sa.Column('code_cim10', sa.String(length=10), nullable=True),
    sa.Column('diagnostics_secondaires', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('plan_traitement', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('suivi_necessaire', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_prochain_rdv', sa.Date(), nullable=True),
    sa.Column('instructions_patient', sa.Text(), nullable=True),
    sa.Column('transcription_ia', sa.Text(), nullable=True),
    sa.Column('resume_ia', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), server_default=sa.text("'en_cours'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['rdv_id'], ['rendez_vous.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_consultation', name='uq_consultations_numero_consultation'),
    sa.UniqueConstraint('rdv_id', name='uq_consultations_rdv_id')
    )
    op.create_index('ix_consultations_medecin_id', 'consultations', ['medecin_id'], unique=False)
    op.create_index('ix_consultations_patient_id', 'consultations', ['patient_id'], unique=False)
    op.create_index('ix_consultations_rdv_id', 'consultations', ['rdv_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('rdv_id', sa.UUID(), nullable=True),
    sa.Column('statut', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('nb_messages_non_lus_patient', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('nb_messages_non_lus_medecin', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dernier_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dernier_message_preview', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['rdv_id'], ['rendez_vous.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_medecin_id', 'conversations', ['medecin_id'], unique=False)
    op.create_index('ix_conversations_patient_id', 'conversations', ['patient_id'], unique=False)
    op.create_index('ix_conversations_rdv_id', 'conversations', ['rdv_id'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('rdv_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('devise', postgresql.ENUM('XAF', 'EUR', 'USD', 'GBP', 'XOF', name='devise_enum'), server_default=sa.text("'XAF'::public.devise_enum"), nullable=False),
    sa.Column('frais_plateforme', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('taux_commission', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.1000'), nullable=False),
    sa.Column('montant_medecin', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('methode', postgresql.ENUM('mtn_momo', 'orange_money', 'carte_visa', 'carte_mastercard', 'virement_bancaire', 'notchpay', 'stripe', 'portefeuille_nere', name='methode_paiement'), nullable=False),
    sa.Column('fournisseur', postgresql.ENUM('cinetpay', 'stripe', 'notchpay', 'interne', name='fournisseur_paiement'), nullable=False),
    sa.Column('statut', postgresql.ENUM('initie', 'en_attente_confirmation', 'confirme', 'echoue', 'rembourse', 'rembourse_partiel', 'annule', 'expire', name='statut_paiement'), server_default=sa.text("'initie'::public.statut_paiement"), nullable=False),
    sa.Column('reference_fournisseur', sa.String(length=200), nullable=True),
    sa.Column('transaction_id_externe', sa.String(length=200), nullable=True),
    sa.Column('url_paiement', sa.String(length=2000), nullable=True),
    sa.Column('date_remboursement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motif_remboursement', sa.Text(), nullable=True),
    sa.Column('montant_rembourse', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reference_remboursement', sa.String(length=200), nullable=True),
    sa.Column('webhook_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('webhook_signature', sa.String(length=500), nullable=True),
    sa.Column('reversi_effectue', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_reversement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_reversement', sa.String(length=200), nullable=True),
    sa.Column('ip_paiement', postgresql.INET(), nullable=True),
    sa.Column('user_agent_paiement', sa.Text(), nullable=True),
    sa.Column('date_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['rdv_id'], ['rendez_vous.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference', name='uq_paiements_reference')
    )
    op.create_index('ix_paiements_medecin_id', 'paiements', ['medecin_id'], unique=False)
    op.create_index('ix_paiements_patient_id', 'paiements', ['patient_id'], unique=False)
    op.create_index('ix_paiements_rdv_id', 'paiements', ['rdv_id'], unique=False)
    op.create_table('documents_medicaux',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('medecin_uploadeur_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_par', sa.UUID(), nullable=False),
    sa.Column('type_document', postgresql.ENUM('resultat_labo', 'imagerie_radio', 'imagerie_echographie', 'imagerie_scanner', 'imagerie_irm', 'compte_rendu_consultation', 'ordonnance_scannee', 'certificat_medical', 'carnet_vaccination', name='type_document_medical'), nullable=False),
    sa.Column('nom_fichier_original', sa.String(length=500), nullable=False),
    sa.Column('nom_fichier_stockage', sa.String(length=500), nullable=False),
    sa.Column('url_stockage', sa.String(length=2000), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('taille_octets', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('est_chiffre', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('cle_chiffrement_ref', sa.String(length=100), nullable=True),
    sa.Column('partage_avec_medecins', sa.ARRAY(sa.UUID()), server_default=sa.text('ARRAY[]::uuid[]'), nullable=False),
    sa.Column('visible_patient', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_document', sa.Date(), nullable=True),
    sa.Column('laboratoire_nom', sa.String(length=200), nullable=True),
    sa.Column('prescripteur_nom', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['medecin_uploadeur_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('expediteur_id', sa.UUID(), nullable=False),
    sa.Column('contenu_chiffre', postgresql.BYTEA(), nullable=False),
    sa.Column('type', postgresql.ENUM('texte', 'image', 'document', 'audio', 'video', 'systeme', name='type_message'), server_default=sa.text("'texte'::public.type_message"), nullable=False),
    sa.Column('fichier_url', sa.String(length=2000), nullable=True),
    sa.Column('fichier_nom', sa.String(length=500), nullable=True),
    sa.Column('fichier_taille', sa.BigInteger(), nullable=True),
    sa.Column('fichier_mime', sa.String(length=100), nullable=True),
    sa.Column('lu_par_destinataire', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date_lecture', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('supprime_par_expediteur', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['expediteur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordonnances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('medecin_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('date_emission', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('statut', postgresql.ENUM('active', 'utilisee', 'partiellement_utilisee', 'expiree', 'annulee', name='statut_ordonnance'), server_default=sa.text("'active'::public.statut_ordonnance"), nullable=False),
    sa.Column('date_utilisation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pharmacie_utilisee', sa.String(length=200), nullable=True),
    sa.Column('qr_code_data', sa.Text(), nullable=False),
    sa.Column('qr_code_url', sa.String(length=1000), nullable=True),
    sa.Column('code_pharmacie', sa.String(length=20), nullable=True),
    sa.Column('signature_numerique', sa.Text(), nullable=True),
    sa.Column('hash_integritet', sa.String(length=64), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('notes_medecin', sa.Text(), nullable=True),
    sa.Column('renouvelable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('nb_renouvellements_max', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('nb_renouvellements', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecins.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_pharmacie', name='uq_ordonnances_code_pharmacie'),
    sa.UniqueConstraint('numero', name='uq_ordonnances_numero')
    )
    op.create_index('ix_ordonnances_consultation_id', 'ordonnances', ['consultation_id'], unique=False)
    op.create_index('ix_ordonnances_medecin_id', 'ordonnances', ['medecin_id'], unique=False)
    op.create_index('ix_ordonnances_patient_id', 'ordonnances', ['patient_id'], unique=False)
    op.create_table('ordonnance_lignes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ordonnance_id', sa.UUID(), nullable=False),
    sa.Column('ordre', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('medicament_nom', sa.String(length=300), nullable=False),
    sa.Column('dci', sa.String(length=300), nullable=True),
    sa.Column('classe_therapeutique', sa.String(length=150), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('forme', postgresql.ENUM('comprimes', 'gelules', 'sirop', 'injectable', 'creme', 'pommade', 'gouttes', 'suppositoire', 'patch', 'inhalateur', 'autre', name='forme_medicament'), nullable=False),
    sa.Column('posologie', sa.String(length=500), nullable=False),
    sa.Column('frequence_par_jour', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('duree_jours', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('avant_repas', sa.Boolean(), nullable=True),
    sa.Column('heure_prise', sa.ARRAY(sa.Time()), nullable=True),
    sa.Column('instructions_speciales', sa.Text(), nullable=True),
    sa.Column('interactions_a_eviter', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ordonnance_id'], ['ordonnances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordonnance_lignes')
    op.drop_index('ix_ordonnances_patient_id', table_name='ordonnances')
    op.drop_index('ix_ordonnances_medecin_id', table_name='ordonnances')
    op.drop_index('ix_ordonnances_consultation_id', table_name='ordonnances')
    op.drop_table('ordonnances')
    op.drop_table('messages')
    op.drop_table('documents_medicaux')
    op.drop_index('ix_paiements_rdv_id', table_name='paiements')
    op.drop_index('ix_paiements_patient_id', table_name='paiements')
    op.drop_index('ix_paiements_medecin_id', table_name='paiements')
    op.drop_table('paiements')
    op.drop_index('ix_conversations_rdv_id', table_name='conversations')
    op.drop_index('ix_conversations_patient_id', table_name='conversations')
    op.drop_index('ix_conversations_medecin_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_consultations_rdv_id', table_name='consultations')
    op.drop_index('ix_consultations_patient_id', table_name='consultations')
    op.drop_index('ix_consultations_medecin_id', table_name='consultations')
    op.drop_table('consultations')
    op.drop_index('ix_chatbot_sessions_rdv_cree_id', table_name='chatbot_sessions')
    op.drop_index('ix_chatbot_sessions_patient_id', table_name='chatbot_sessions')
    op.drop_index('ix_chatbot_sessions_medecin_id', table_name='chatbot_sessions')
    op.drop_table('chatbot_sessions')
    op.drop_index('ix_avis_rdv_id', table_name='avis')
    op.drop_index('ix_avis_patient_id', table_name='avis')
    op.drop_index('ix_avis_medecin_id', table_name='avis')
    op.drop_table('avis')
    op.drop_index('ix_rendez_vous_structure_id', table_name='rendez_vous')
    op.drop_index('ix_rendez_vous_patient_id', table_name='rendez_vous')
    op.drop_index('ix_rendez_vous_medecin_id', table_name='rendez_vous')
    op.drop_index('ix_rendez_vous_date_heure_debut', table_name='rendez_vous')
    op.drop_table('rendez_vous')
    op.drop_table('medecin_specialites')
    op.drop_index('ix_dossiers_medicaux_medecin_traitant_id', table_name='dossiers_medicaux')
    op.drop_table('dossiers_medicaux')
    op.drop_table('disponibilites')
    op.drop_table('medecins')
    op.drop_table('audit_logs')
    op.drop_table('structures')
    op.drop_table('sessions')
    op.drop_table('patients')
    op.drop_index('ix_notifications_utilisateur_id', table_name='notifications')
    op.drop_index('ix_notifications_statut', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('users')
    op.drop_table('specialites')
    # ### end Alembic commands ###
